### ISSUE TITLE
Bug: stack.ls does not increment offset correctly

### ISSUE THREAD

**Issue by MartijnSanders** [Paradoxis/TransIP-STACK-API#8]
in stack.ls on line 175 the offset is incremented wrongly
`offset += self.ls_buffer_limit`
should be 
`offset += len(files['nodes'])`

**Comment by Paradoxis** [comment]
Thanks for the heads up! Releasing fixed version shortly 🚀

**Comment by Paradoxis** [comment]
Latest version [1.2.3](https://pypi.org/project/transip-stack-api/1.2.3/) pushed to PyPi
